version: "3"
project:
  name: warmscreen
  image: node:20
  
services:
  - name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: warmscreen
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warmscreen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  - name: redis
    image: redis:7
    ports:
      - "6379:6379"

ports:
  - name: web
    port: 3000
    protocol: http
  - name: api
    port: 3001
    protocol: http

volumes:
  - name: postgres_data

commands:
  setup: |
    npm install
    cd packages/database && npm install
    cd ../../apps/api && npm install
    cd ../web && npm install
  
  dev: |
    npm run dev
  
  db:setup: |
    cd packages/database
    cp .env.example .env
    npx prisma generate
    npx prisma db push
  
  db:migrate: |
    cd packages/database
    npx prisma migrate dev
  
  db:studio: |
    cd packages/database
    npx prisma studio

environment:
  DATABASE_URL: "postgresql://warmscreen:password@postgres:5432/warmscreen?schema=public"
  REDIS_URL: "redis://redis:6379"
  NODE_ENV: "development"
